### ISSUE TITLE
TileLink memory master model problem

### ISSUE THREAD

**Issue by chick** [ucb-bar/rocket-dsp-utils#1]
Inside MemMasterSpec.scala there is an open issue related to TileLink memory master model (line 131). 
Besides using AXI4 memory master model, we've been trying to test our peripherals using TileLink memory master model as well and the same assertion error as noted in the MemMasterSpec.scala file occurs.
That would be cool if it gets fixed as well in this iteration since we find those memory master models very useful for testing our DspBlocks.
This is something we can't do ourselves, since it is far beyond our work scope.

**Comment by milovanovic** [comment]
This issue is [fixed](https://github.com/ucb-bar/rocket-dsp-utils/pull/13).
