### ISSUE TITLE
ShiftRegisterMem should provide also single port SRAM implementation

### ISSUE THREAD

**Issue by chick** [ucb-bar/rocket-dsp-utils#2]
There is a note inside craft/ShiftRegisterMem.scala that ShiftRegisterMem should provide also single port SRAM iplementation but there are some bugs in the current version.
We would need to have this fixed eventually, but perhaps we can try to fix it on our side also.

**Comment by milovanovic** [comment]
This issue is fixed by the [corresponding](https://github.com/ucb-bar/rocket-dsp-utils/pull/8) pull request.
